projeto_imoveis:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres 
      port: 5432
      user: airflow
      pass: airflow
      dbname: airflow
      schema: dbt_imoveis
      threads: 4